name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-test-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Archive build
        if: github.ref == 'refs/heads/dev'
        run: |
          mkdir -p dist
          if (Test-Path build) { Copy-Item -Path build/* -Destination dist/ -Recurse }

      - name: Upload build artifact
        if: github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v4
        with:
          name: autopilot-build
          path: dist/**

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/dev'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      - name: Deploy (placeholder)
        if: github.ref == 'refs/heads/dev'
        run: echo "Deploying... (позже заменим на например, автоматическое уведомление в Telegram/Discord о готовом билде.)"
